
getting data in to r from excel
```{r}
#library(readxl)
#data <- read_excel("FILE_PATH/NAME")
```
#put files in githib for storage
how to import a csv
```{r}
library(readr)
iris <- read_csv("/Users/zacharydawson/Desktop/newbook-r/iris.csv")
```
head data or view the first few lines of data 
```{r}
head(Loblolly)
```

```{r}
# describe(Loblolly)
# In RStudio displays information about the data set and its source in the
# Help Window

```
 
```{r}
nrow(Loblolly)

```

```{r}
length(unique(Loblolly$Seed))

```

 
```{r}
sort(unique(Loblolly$Seed))
```
 
sumarise data
```{r}
summary(OrchardSprays)
```
#group the length and the width is seperate data sets both with the variaty still there and then merge back tougher 
how to 
```{r}
x <- data()
# x is now a list
 
y <- as.data.frame(x$results)
y <- y[,3:4]
# This gives a data frame of name and description, 104 data sets
 

```


```{r}
library(tibble)
library(tidyr)

#data
mtcars1 <- mtcars
head(mtcars1)

#pivot_longer
mt_long <- pivot_longer(mtcars1,
             cols = mpg:carb,
             names_to = "Category",
             values_to = "Value"
            
)

head(mt_long)
```

```{r}

```

```{r}
library(ggplot2)

# data
data <- data.frame(
  name=c("A","B","C","D","E") ,  
  value=c(3,12,5,18,45)
  )

# Barplot
ggplot(data, aes(x=name, y=value)) + 
  geom_bar(stat = "identity")
```

```{r}
library(ggplot2)
ggplot(data= diamonds)+
  geom_bar(
    mapping = aes(x = cut, fill = clarity),
    position = "dodge"
  )
```


```{r}
library(ggplot2)
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy, color = class))#Colour also works
```

```{r}
ggplot(data = mpg, mapping = aes(x = displ,y = hwy)) +
  geom_point(mapping = aes(color = class)) +
  geom_smooth()
```












